# Generated by Django 3.1.3 on 2020-11-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_news', '0006_article_bulk_ref'),
        ('users', '0004_auto_20201121_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='user', to='fetch_news.Category'),
        ),
    ]
