# Generated by Django 3.1.3 on 2020-11-21 12:45

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
