version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: /start
    volumes:
      - .:/newsapp
    ports:
      - "8000:8000"
    depends_on:
      - db
