version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: /start
    volumes:
      - .:/newsapp
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  redis:
    image: "redis:alpine"
  celery:
    build: .
    command: /start-celery
    volumes:
      - .:/newsapp
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
  celery-beat:
    build: .
    command: /start-celerybeat
    volumes:
      - .:/newsapp
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
