# Generated by Django 3.1.3 on 2020-11-21 06:45

from django.db import migrations


def add_predefined_category(apps, schema_editor):
    Category = apps.get_model("fetch_news", "Category")
    category_list = []
    predefined_category = [
        'Social', 'Political', 'Sports', 'Educational', 'Tech', 'General'
    ]
    for cat in predefined_category:
        category_list.append(Category(name=cat))
    Category.objects.bulk_create(category_list)
    return


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_news', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_predefined_category),
    ]
