# Generated by Django 3.1.3 on 2020-11-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_news', '0005_auto_20201121_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bulk_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
